spring:
  application:
    name: /ConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/musa2333/configServer.git
          username: musa2333
          password:
          search-paths: '{application}'
      zookeepr:
        connect-string: 47.101.191.170:2181
        discovery:
          root: /jobs
          instance-port: ${server.port}
      label: master
env:
  dev